/**
 * StarField — deterministic scattered SVG stars simulating a night sky (prototype v4.2).
 *
 * Used on Sleep Dashboard (11) and Sleep Log Entry (33). Fully decorative; hidden
 * from screen readers. Positions are generated by a seeded LCG PRNG (mulberry32)
 * so snapshots remain stable across test runs.
 *
 * @example
 *   <StarField width={375} height={260} count={30} seed={7} />
 */

import React from "react";
import { View, type StyleProp, type ViewStyle } from "react-native";
import Svg, { Circle } from "react-native-svg";

import { useTheme } from "@/shared/theme/useTheme";

export interface StarFieldProps {
  /** Number of star dots. Defaults to 24. */
  count?: number;
  /** Canvas width in dp (required — usually matches screen/container width). */
  width: number;
  /** Canvas height in dp (required — usually matches container height). */
  height: number;
  /** PRNG seed for deterministic positions. Defaults to 42. */
  seed?: number;
  /** Optional outer style override. */
  style?: StyleProp<ViewStyle>;
  testID?: string;
}

/**
 * mulberry32 — fast seeded 32-bit LCG that returns floats in [0, 1).
 * Deterministic: same seed always produces the same sequence.
 */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return function next(): number {
    s += 0x6d2b79f5;
    let z = s;
    z = Math.imul(z ^ (z >>> 15), z | 1);
    z ^= z + Math.imul(z ^ (z >>> 7), z | 61);
    return ((z ^ (z >>> 14)) >>> 0) / 4294967296;
  };
}

interface Star {
  cx: number;
  cy: number;
  r: number;
  opacity: number;
}

function generateStars(count: number, width: number, height: number, seed: number): Star[] {
  const rand = mulberry32(seed);
  return Array.from({ length: count }, () => ({
    cx: rand() * width,
    cy: rand() * height,
    r: 0.5 + rand() * 2.5, // 0.5–3 px
    opacity: 0.3 + rand() * 0.6, // 0.3–0.9
  }));
}

export function StarField({
  count = 24,
  width,
  height,
  seed = 42,
  style,
  testID,
}: StarFieldProps): React.ReactElement {
  const { palette } = useTheme();

  const stars = React.useMemo(
    () => generateStars(count, width, height, seed),
    [count, width, height, seed],
  );

  const starColor = palette.warm[50];

  // Fully decorative — hidden from all accessibility APIs.
  // NOTE: Per the 2026-05-15 audit, the RN-only a11y props (`accessibilityElementsHidden`,
  // `importantForAccessibility`) cannot be applied directly to <Svg>: react-native-svg's
  // web renderer spreads unknown props through to the underlying <svg> DOM element,
  // triggering a React DOM-attribute warning. Wrap in a <View> that carries those props
  // instead (react-native-web silently drops them from the <div> output).
  return (
    <View
      testID={testID}
      style={[{ width, height }, style]}
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
      pointerEvents="none"
    >
      <Svg
        width={width}
        height={height}
      >
      {stars.map((star, i) => (
        <Circle
          key={i}
          cx={star.cx}
          cy={star.cy}
          r={star.r}
          fill={starColor}
          fillOpacity={star.opacity}
        />
      ))}
      </Svg>
    </View>
  );
}
