// Auto-generated theme from Figma Design System
// File ID: gNHpWsoal7dlP2WJpoq1Ob
// Generated: 2025-08-02T00:57:13.108Z

// Merge with existing theme
import {
  colors as existingColors,
  typography as existingTypography,
} from "../styles/theme";

export const figmaTokens = {
  colors: {
    blue_60: "Blue/60",
    blue_30: "Blue/30",
    blue_70: "Blue/70",
    teal_20: "Teal/20",
    gray_20: "Gray/20",
    gray_60: "Gray/60",
    gray_90: "Gray/90",
    gray_10: "Gray/10",
    gray_30: "Gray/30",
    gray_40: "Gray/40",
    gray_50: "Gray/50",
    gray_70: "Gray/70",
    gray_80: "Gray/80",
    gray_100: "Gray/100",
    teal_30: "Teal/30",
    gray_white: "Gray/White",
    blue_10: "Blue/10",
    blue_20: "Blue/20",
    teal_10: "Teal/10",
    teal_50: "Teal/50",
    teal_70: "Teal/70",
    blue_40: "Blue/40",
    blue_50: "Blue/50",
    blue_80: "Blue/80",
    blue_90: "Blue/90",
    blue_100: "Blue/100",
    teal_40: "Teal/40",
    teal_60: "Teal/60",
    teal_80: "Teal/80",
    teal_90: "Teal/90",
    teal_100: "Teal/100",
    red_10: "Red/10",
    red_20: "Red/20",
    red_30: "Red/30",
    red_40: "Red/40",
    red_50: "Red/50",
    red_60: "Red/60",
    red_70: "Red/70",
    red_80: "Red/80",
    red_90: "Red/90",
    red_100: "Red/100",
    cyan_10: "Cyan/10",
    cyan_20: "Cyan/20",
    cyan_30: "Cyan/30",
    cyan_40: "Cyan/40",
    cyan_50: "Cyan/50",
    cyan_60: "Cyan/60",
    cyan_70: "Cyan/70",
    cyan_80: "Cyan/80",
    cyan_90: "Cyan/90",
    cyan_100: "Cyan/100",
    purple_10: "Purple/10",
    purple_20: "Purple/20",
    purple_30: "Purple/30",
    purple_40: "Purple/40",
    purple_50: "Purple/50",
    purple_60: "Purple/60",
    purple_70: "Purple/70",
    purple_80: "Purple/80",
    purple_90: "Purple/90",
    purple_100: "Purple/100",
    mindful_brown_white: "Mindful Brown/White",
    mindful_brown_60: "Mindful Brown/60",
    mindful_brown_80: "Mindful Brown/80",
    mindful_brown_20: "Mindful Brown/20",
    empathy_orange_40: "Empathy Orange/40",
    optimistic_gray_40: "Optimistic Gray/40",
    optimistic_gray_60: "Optimistic Gray/60",
    serenity_green_10: "Serenity Green/10",
    serenity_green_30: "Serenity Green/30",
    serenity_green_20: "Serenity Green/20",
    serenity_green_50: "Serenity Green/50",
    mindful_brown_10: "Mindful Brown/10",
    empathy_orange_10: "Empathy Orange/10",
    mindful_brown_30: "Mindful Brown/30",
    empathy_orange_20: "Empathy Orange/20",
    gentle_purple_40: "Gentle Purple/40",
    gentle_purple_20: "Gentle Purple/20",
    zen_yellow_50: "Zen Yellow/50",
    zen_yellow_20: "Zen Yellow/20",
    optimistic_gray_20: "Optimistic Gray/20",
    mindful_brown_100: "Mindful Brown/100",
    optimistic_gray_30: "Optimistic Gray/30",
    mindful_gray_100: "Mindful Gray/100",
    serenity_green_100: "Serenity Green/100",
    serenity_green_40: "Serenity Green/40",
    mindful_brown_40: "Mindful Brown/40",
    mindful_brown_50: "Mindful Brown/50",
    zen_yellow_10: "Zen Yellow/10",
    zen_yellow_100: "Zen Yellow/100",
    zen_yellow_30: "Zen Yellow/30",
    gentle_purple_30: "Gentle Purple/30",
    gentle_purple_10: "Gentle Purple/10",
    gentle_purple_100: "Gentle Purple/100",
    mindful_brown_70: "Mindful Brown/70",
    serenity_green_60: "Serenity Green/60",
    empathy_orange_100: "Empathy Orange/100",
    empathy_orange_30: "Empathy Orange/30",
    optimistic_gray_10: "Optimistic Gray/10",
    optimistic_gray_100: "Optimistic Gray/100",
    optimistic_gray_50: "Optimistic Gray/50",
    mindful_gray_white: "Mindful Gray/White",
    systemorange_light: "SystemOrange / Light",
    zen_yellow_40: "Zen Yellow/40",
    gentle_purple_80: "Gentle Purple/80",
    empathy_orange_80: "Empathy Orange/80",
    optimistic_gray_80: "Optimistic Gray/80",
    green_dark: "Green/Dark",
    zen_yellow_80: "Zen Yellow/80",
    serenity_green_80: "Serenity Green/80",
    empathy_orange_50: "Empathy Orange/50",
    serenity_green_70: "Serenity Green/70",
    empathy_orange_70: "Empathy Orange/70",
    empathy_orange_60: "Empathy Orange/60",
    optimistic_gray_70: "Optimistic Gray/70",
    zen_yellow_70: "Zen Yellow/70",
    gentle_purple_70: "Gentle Purple/70",
    gentle_purple_50: "Gentle Purple/50",
    mindful_brown_90: "Mindful Brown/90",
    empathy_orange_90: "Empathy Orange/90",
    zen_yellow_90: "Zen Yellow/90",
    wireframe_color_palette_gray_1: "Wireframe/Color Palette/Gray 1",
    green_medium: "Green/Medium",
    green_light: "Green/Light",
    mindful_brown_100_alpha_48: "Mindful Brown/100 Alpha 48%",
    mindful_brown_100_alpha_64: "Mindful Brown/100 Alpha 64%",
    mindful_brown_100_alpha_32: "Mindful Brown/100 Alpha 32%",
    gentle_purple_60: "Gentle Purple/60",
    black_black: "Black / Black",
    neutral_active: "Neutral/Active",
    gray_black: "Gray/Black",
  },
  typography: {
    display_lg_bold: "Display lg/Bold",
    display_md_bold: "Display md/Bold",
    display_sm_bold: "Display sm/Bold",
    paragraph_2xl: "Paragraph/2xl",
    paragraph_xl: "Paragraph/xl",
    paragraph_lg: "Paragraph/lg",
    paragraph_md: "Paragraph/md",
    paragraph_sm: "Paragraph/sm",
    paragraph_xs: "Paragraph/xs",
    label_2xl: "Label/2xl",
    label_xl: "Label/xl",
    label_lg: "Label/lg",
    label_md: "Label/md",
    label_sm: "Label/sm",
    label_xs: "Label/xs",
    heading_xl_bold: "Heading xl/Bold",
    heading_lg_bold: "Heading lg/Bold",
    heading_2xl_bold: "Heading 2xl/Bold",
    heading_md_bold: "Heading md/Bold",
    heading_sm_bold: "Heading sm/Bold",
    heading_xs_bold: "Heading xs/Bold",
    heading_2xl_extrabold: "Heading 2xl/ExtraBold",
    heading_xl_extrabold: "Heading xl/ExtraBold",
    heading_lg_extrabold: "Heading lg/ExtraBold",
    heading_md_extrabold: "Heading md/ExtraBold",
    heading_sm_extrabold: "Heading sm/ExtraBold",
    heading_xs_extrabold: "Heading xs/ExtraBold",
    text_2xl_bold: "Text 2xl/Bold",
    text_xl_bold: "Text xl/Bold",
    text_lg_bold: "Text lg/Bold",
    text_md_bold: "Text md/Bold",
    text_sm_bold: "Text sm/Bold",
    text_xs_bold: "Text xs/Bold",
    text_2xl_semibold: "Text 2xl/SemiBold",
    text_xl_semibold: "Text xl/SemiBold",
    text_lg_semibold: "Text lg/SemiBold",
    text_md_semibold: "Text md/SemiBold",
    text_sm_semibold: "Text sm/SemiBold",
    text_xs_semibold: "Text xs/SemiBold",
    text_2xl_extrabold: "Text 2xl/ExtraBold",
    text_xl_extrabold: "Text xl/ExtraBold",
    text_lg_extrabold: "Text lg/ExtraBold",
    text_md_extrabold: "Text md/ExtraBold",
    text_sm_extrabold: "Text sm/ExtraBold",
    text_xs_extrabold: "Text xs/ExtraBold",
    heading_2xl_semibold: "Heading 2xl/SemiBold",
    heading_xl_semibold: "Heading xl/SemiBold",
    heading_lg_semibold: "Heading lg/SemiBold",
    heading_md_semibold: "Heading md/SemiBold",
    heading_sm_semibold: "Heading sm/SemiBold",
    heading_xs_semibold: "Heading xs/SemiBold",
    display_lg_extrabold: "Display lg/ExtraBold",
    display_md_extrabold: "Display md/ExtraBold",
    display_sm_extrabold: "Display sm/ExtraBold",
    text_2xs_extrabold: "Text 2xs/ExtraBold",
    text_2xs_semibold: "Text 2xs/SemiBold",
    text_2xs_bold: "Text 2xs/Bold",
    heading_sm_regular: "Heading sm/Regular",
    heading_xl_medium: "Heading xl/Medium",
    text_xl_medium: "Text xl/Medium",
  },
  spacing: {
    grids_spacing: 1440,
  },
  borderRadius: {},
  shadows: {},
  components: {
    buttons_2: {
      name: "🔒 Buttons 2",
      type: "FRAME",
      width: 1440,
      height: 2418,
      borderRadius: 0,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      backgroundColor: null,
      shadows: [],
    },
    buttons_1: {
      name: "🔒 Buttons 1",
      type: "FRAME",
      width: 1440,
      height: 2050,
      borderRadius: 0,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      backgroundColor: null,
      shadows: [],
    },
    cards_lists_1: {
      name: "🔒 Cards & Lists 1",
      type: "FRAME",
      width: 1440.189697265625,
      height: 5457,
      borderRadius: 0,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      backgroundColor: null,
      shadows: [],
    },
    cards_lists_2: {
      name: "🔒 Cards & Lists 2",
      type: "FRAME",
      width: 1440,
      height: 3538,
      borderRadius: 0,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      },
      backgroundColor: null,
      shadows: [],
    },
  },
};

export const mergedTheme = {
  colors: {
    ...existingColors,
    figma: figmaTokens.colors,
  },
  typography: {
    ...existingTypography,
    figma: figmaTokens.typography,
  },
  spacing: {
    ...figmaTokens.spacing,
  },
  components: {
    ...figmaTokens.components,
  },
};

export default mergedTheme;
